version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ed-match-data-dropper-stack"
s3_bucket = "ed-serverless-deployments"
s3_prefix = "ed-match-data-dropper-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
