AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for the MatchData.Dropper serverless application. Spins up a Lambda that receives events from an S3 Bucket.

Globals: # https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  Function:
    Runtime: dotnetcore2.1
    Timeout: 30
    Environment: # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        PARAM1: VALUE

Resources: # Implicitly generated resources https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#s3
  MatchDataBucket:
    Type: AWS::S3::Bucket
  MatchDataDropper:
    Type: AWS::Serverless::Function # Creates a Lambda function, role and event source mappings https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/MatchData.Dropper/
      Handler: MatchData.Dropper::MatchData.Dropper.Function::FunctionHandler
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
              Resource: '*'
      Events: # Define events that trigger this function
        MatchDataCSVUpload:
          Type: S3 # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types
          Properties:
            Bucket: !Ref MatchDataBucket # bucket must be created in the same template
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
      Tags:
        AppNameTag: ThumbnailApp
        DepartmentNameTag: ThumbnailDepartment